# Generated by Django 4.1.4 on 2023-01-10 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_created_at_employee_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogposts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
